<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <script src="./dist/React.js"></script>
   <!--<script src="./test/react.development.js"></script>
    <script src="./test/react-dom.development.js"></script>-->

    <script src="./test/babel.js"></script>
   

</head>
<body>

    <pre style="background:#002fa7">
        1111
    </pre>
    <pre style="background:blue">
        1111
</pre>
    <div id='example'></div>
    <div id='console'></div>
    <script type='text/babel'>
        var expect = function(a) {
            return {
                toBe: function(b) {
                    console.log(a,"\n", b, a === b)
                }
            }
        }
        var PropTypes = React.PropTypes
        var log = []
        var container = document.getElementById("example")
        var div = container;
        function logger(e){
           log.push(e)
        }
    
var ErrorBoundary = class extends React.Component {
      constructor(props) {
        super(props);
        this.state = {error: null};
        logger(`${this.props.logName} constructor`);
      }
      render() {
        if (this.state.error && !this.props.forceRetry) {
          logger(`${this.props.logName} render error`);
          console.log("补救。。。。。")
          var a = this.props.renderError(this.state.error, this.props);
         
          return a
        }
        logger(`${this.props.logName} render success`);
        return <div className="ErrorBoundary">{this.props.children}</div>;
      }
      componentDidCatch(error) {
        logger(`${this.props.logName} componentDidCatch`);
        this.setState({error});
      }
      componentWillMount() {
        logger(`${this.props.logName} componentWillMount`);
      }
      componentDidMount() {
        logger(`${this.props.logName} componentDidMount`);
      }
      componentWillReceiveProps() {
        logger(`${this.props.logName} componentWillReceiveProps`);
      }
      componentWillUpdate() {
        logger(`${this.props.logName} componentWillUpdate`);
      }
      componentDidUpdate() {
        logger(`${this.props.logName} componentDidUpdate`);
      }
      componentWillUnmount() {
        logger(`${this.props.logName} componentWillUnmount`);
      }
    };
    ErrorBoundary.defaultProps = {
      logName: 'ErrorBoundary',
      renderError(error, props) {
          console.log(error, props, error.message,"!!!")
        return (
          <div ref={props.errorMessageRef}>
            Caught an error: {error.message}.
          </div>
        );
      },
    };

    var BrokenRender = class extends React.Component {
      constructor(props) {
        super(props);
        logger('BrokenRender constructor');
      }
      render() {
        logger('BrokenRender render [!]');
        throw new Error('Hello');
      }
      componentWillMount() {
        logger('BrokenRender componentWillMount');
      }
      componentDidMount() {
        logger('BrokenRender componentDidMount');
      }
      componentWillReceiveProps() {
        logger('BrokenRender componentWillReceiveProps');
      }
      componentWillUpdate() {
        logger('BrokenRender componentWillUpdate');
      }
      componentDidUpdate() {
        logger('BrokenRender componentDidUpdate');
      }
      componentWillUnmount() {
        logger('BrokenRender componentWillUnmount');
      }
    };
    var RetryErrorBoundary = class extends React.Component {
            constructor(props) {
                super(props);
                logger("RetryErrorBoundary constructor");
            }
            render() {
                logger("RetryErrorBoundary render");
                return <BrokenRender />;
            }
            componentWillMount() {
                logger("RetryErrorBoundary componentWillMount");
            }
            componentDidMount() {
                logger("RetryErrorBoundary componentDidMount");
            }
            componentWillUnmount() {
                logger("RetryErrorBoundary componentWillUnmount");
            }
            componentDidCatch(error) {
                logger("RetryErrorBoundary componentDidCatch [!]");
                // In Fiber, calling setState() (and failing) is treated as a rethrow.
                this.setState({});
            }
        };
    //var container = document.createElement("div");
    ReactDOM.render(
        <ErrorBoundary>
            <RetryErrorBoundary>
                <BrokenRender />
            </RetryErrorBoundary>
        </ErrorBoundary>,
        container
    );
    expect(container.firstChild.textContent).toBe("Caught an error: Hello.");
    expect(log.join("\n")).toBe([
        "ErrorBoundary constructor",
        "ErrorBoundary componentWillMount",
        "ErrorBoundary render success",
        "RetryErrorBoundary constructor",
        "RetryErrorBoundary componentWillMount",
        "RetryErrorBoundary render",
        "BrokenRender constructor",
        "BrokenRender componentWillMount",
        "BrokenRender render [!]",
        // In Fiber, failed error boundaries render null before attempting to recover
        "RetryErrorBoundary componentDidMount",
        "RetryErrorBoundary componentDidCatch [!]",
        "ErrorBoundary componentDidMount",
        // Retry
        "RetryErrorBoundary render",
        "BrokenRender constructor",
        "BrokenRender componentWillMount",
        "BrokenRender render [!]",
        // This time, the error propagates to the higher boundary
        "RetryErrorBoundary componentWillUnmount",
        "ErrorBoundary componentDidCatch",
        // Render the error
        "ErrorBoundary componentWillUpdate",
        "ErrorBoundary render error",
        "ErrorBoundary componentDidUpdate"
    ].join("\n"));

    log.length = 0;
   // ReactDOM.unmountComponentAtNode(container);
 //   expect(log+"").toBe(["ErrorBoundary componentWillUnmount"]+"");
        
        
               </script>
</body>

</html>